import os
import re
import uuid
import json
from datetime import datetime, timezone
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

LOG_PATH = "audit_log.jsonl"

app = Flask(__name__)
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)


def classify_with_llm(text):
    """Call Groq to score the text. Returns (score, reasoning) where 0.0=human, 1.0=AI."""
    prompt = (
        "You are an AI content detection assistant. Analyze the text below and assess "
        "whether it was written by a human or generated by an AI.\n\n"
        "Return ONLY a JSON object with this exact structure:\n"
        '{"score": <float between 0.0 and 1.0>, "reasoning": "<one sentence>"}\n\n'
        "score meaning: 0.0 = definitely human, 1.0 = definitely AI.\n\n"
        f"Text to analyze:\n{text}"
    )
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
        response_format={"type": "json_object"},
    )
    parsed = json.loads(response.choices[0].message.content)
    return float(parsed["score"]), parsed.get("reasoning", "")


def _normalize(value, human_val, ai_val):
    """Scale value to [0,1] where 0=human-like, 1=AI-like."""
    span = ai_val - human_val
    if span == 0:
        return 0.5
    return max(0.0, min(1.0, (value - human_val) / span))

def compute_heuristic_score(text):
    """
    Three stylometric signals:
      - TTR: lower lexical diversity → AI-like
      - Sentence length CV: lower variance → AI-like (uniform lengths)
      - Avg word length: longer words → AI-like (formal vocabulary)
    Returns (heuristic_score, details_dict), score in [0.0=human, 1.0=AI].
    """
    words = text.lower().split()
    if not words:
        return 0.5, {}

    # TTR — reference: human ~0.70, AI ~0.60
    ttr = len(set(words)) / len(words)
    ttr_score = _normalize(ttr, 0.70, 0.60)

    # Sentence length coefficient of variation — reference: human ~0.50, AI ~0.25
    sentences = [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]
    lengths = [len(s.split()) for s in sentences] if sentences else [len(words)]
    mean_len = sum(lengths) / len(lengths)
    if len(lengths) > 1:
        sd = (sum((l - mean_len) ** 2 for l in lengths) / len(lengths)) ** 0.5
        len_cv = sd / mean_len if mean_len > 0 else 0.0
    else:
        len_cv = 0.0  # single sentence → no variance → AI-like
    len_cv_score = _normalize(len_cv, 0.50, 0.25)

    # Average word length — reference: human ~4.5 chars, AI ~5.5 chars
    avg_word_len = sum(len(w) for w in words) / len(words)
    word_len_score = _normalize(avg_word_len, 4.5, 5.5)

    heuristic_score = round((ttr_score + len_cv_score + word_len_score) / 3, 4)
    return heuristic_score, {
        "ttr": round(ttr, 4),
        "len_cv": round(len_cv, 4),
        "avg_word_length": round(avg_word_len, 2),
        "ttr_score": round(ttr_score, 4),
        "len_cv_score": round(len_cv_score, 4),
        "word_len_score": round(word_len_score, 4),
    }


def generate_label(confidence):
    """Map confidence score to (result, plain-language label string)."""
    pct = round(confidence * 100)
    if confidence <= 0.35:
        return "human", (
            f"This content appears to have been written by a person. "
            f"Our detection system is {pct}% confident in this result."
        )
    elif confidence > 0.65:
        return "ai", (
            f"This content appears to have been generated by an AI. "
            f"Our detection system is {pct}% confident in this result. "
            f"If this is incorrect, the creator can submit an appeal."
        )
    else:
        return "uncertain", (
            f"Our detection system could not confidently determine whether this content "
            f"was written by a person or generated by AI (confidence: {pct}%). "
            f"If you believe this classification is incorrect, the creator can submit an appeal."
        )


def log_event(entry):
    entry["timestamp"] = datetime.now(timezone.utc).isoformat()
    with open(LOG_PATH, "a") as f:
        f.write(json.dumps(entry) + "\n")


def read_log(limit=20):
    try:
        with open(LOG_PATH) as f:
            lines = f.readlines()
    except FileNotFoundError:
        return []
    return [json.loads(line) for line in reversed(lines[-limit:])]


def find_log_entry(content_id):
    """Return the entry dict for content_id, or None if not found."""
    try:
        with open(LOG_PATH) as f:
            for line in f:
                entry = json.loads(line)
                if entry.get("content_id") == content_id:
                    return entry
    except FileNotFoundError:
        pass
    return None


def update_log_entry(content_id, updates):
    """Rewrite the log file with updates applied to the matching entry."""
    try:
        with open(LOG_PATH) as f:
            lines = f.readlines()
    except FileNotFoundError:
        return False
    new_lines = []
    found = False
    for line in lines:
        entry = json.loads(line)
        if entry.get("content_id") == content_id:
            entry.update(updates)
            found = True
        new_lines.append(json.dumps(entry) + "\n")
    if found:
        with open(LOG_PATH, "w") as f:
            f.writelines(new_lines)
    return found


@app.route("/")
def home():
    return "Provenance Guard is running."


@app.route("/log", methods=["GET"])
def get_log():
    return jsonify({"entries": read_log()})


@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()
    if not data:
        return jsonify({"error": "Request body must be JSON"}), 400
    text = data.get("text") or data.get("content")
    if not text:
        return jsonify({"error": "Missing required field: text"}), 400
    creator_id = data.get("creator_id", "anonymous")

    llm_score, llm_reasoning = classify_with_llm(text)
    heuristic_score, heuristic_details = compute_heuristic_score(text)
    confidence = round(0.6 * llm_score + 0.4 * heuristic_score, 4)
    attribution, label = generate_label(confidence)

    entry = {
        "content_id": str(uuid.uuid4()),
        "creator_id": creator_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
        "signals": {
            "llm_score": round(llm_score, 4),
            "llm_reasoning": llm_reasoning,
            "heuristic_score": heuristic_score,
            **heuristic_details,
        },
        "status": "classified",
    }
    log_event(entry)

    return jsonify({k: entry[k] for k in ("content_id", "attribution", "confidence", "label", "signals", "status")})


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()
    if not data:
        return jsonify({"error": "Request body must be JSON"}), 400
    content_id = data.get("content_id")
    reasoning = data.get("creator_reasoning")
    if not content_id:
        return jsonify({"error": "Missing required field: content_id"}), 400
    if not reasoning:
        return jsonify({"error": "Missing required field: creator_reasoning"}), 400

    existing = find_log_entry(content_id)
    if existing is None:
        return jsonify({"error": f"No submission found with content_id: {content_id}"}), 404
    if existing.get("status") == "under_review":
        return jsonify({"error": "An appeal has already been filed for this submission"}), 409

    appeal_id = str(uuid.uuid4())
    update_log_entry(content_id, {
        "status": "under_review",
        "appeal": {
            "appeal_id": appeal_id,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "creator_reasoning": reasoning,
        },
    })

    return jsonify({
        "appeal_id": appeal_id,
        "content_id": content_id,
        "status": "under_review",
        "message": "Your appeal was received and is under review.",
    })


if __name__ == "__main__":
    app.run(port=5000, debug=True)
